cache = {
    'http://libproxy.smu.edu.sg/login?url=http://link.springer.com/10.1007/978-1-4842-9367-6': 0,
    'http://libproxy.smu.edu.sg/login?url=http://link.springer.com/10.1007/978-1-4842-9579-3': 1,
    'http://libproxy.smu.edu.sg/login?url=https://doi.org/10.1126/science.adi0656?locatt=mode:legacy': 2,
    'http://libproxy.smu.edu.sg/login?url=https://www.tandfonline.com/doi/abs/10.1080/08956308.2023.2213102': 3,
    'http://libproxy.smu.edu.sg/login?url=https://www.proquest.com/docview/2352323896?pq-origsite=primo': 4,
    'http://libproxy.smu.edu.sg/login?url=https://doi.ieeecomputersociety.org/10.1109/MS.2023.3300574': 5,
}

cache_summary = {
    'http://libproxy.smu.edu.sg/login?url=http://link.springer.com/10.1007/978-1-4842-9367-6': "The document 'Generative AI: How ChatGPT and Other AI Tools Will Revolutionize Business' by Tom Taulli delves into the transformative potential of generative AI, with particular attention to tools like ChatGPT. It references the OpenAI Playground as a testing space for AI prompts. The document also mentions a business deal involving Microsoft's cloud platform, Azure. A significant portion of the text is dedicated to enhancing the success rate of AI implementations. Key steps include identifying the problem, forming a team, crafting the AI model, and deploying and monitoring the system. The importance of addressing organizational pain points is emphasized.",
    'http://libproxy.smu.edu.sg/login?url=http://link.springer.com/10.1007/978-1-4842-9579-3': "The document is focused on 'Design Thinking', which is described as a combination of strategic and creative processes and principles used in planning and creating products that address human-centered design challenges. The text emphasizes the importance of design and innovation, highlighting areas such as User Interface (UI) and User Experience (UX) Design, Psychology of Design, Human-Computer Interaction (HCI), Ergonomic Design, Product Development, Virtual and Mixed Reality (VR/XR), Smart Homes, Accessibility, Sustainability, Learning and Instructional Design, and best practices. The series aims to guide designers, developers, and other professionals in understanding the latest in design thinking.",
    'http://libproxy.smu.edu.sg/login?url=https://doi.org/10.1126/science.adi0656?locatt=mode:legacy': "The document, sourced from 'science.org', addresses the impact of artificial intelligence (AI) on the workforce. It discusses the uncertainty surrounding whether AI will have a positive or negative effect on specific jobs. The content emphasizes that while many jobs might be influenced by AI, especially classification tasks like image recognition, it doesn't necessarily mean these jobs will be replaced. For instance, radiologists may be affected due to AI's capabilities in image classification. Research has shown that millions of jobs could be impacted by generative AI, like large language models (LLMs), but this might lead to increased productivity and wages in some cases.",
    'http://libproxy.smu.edu.sg/login?url=https://www.tandfonline.com/doi/abs/10.1080/08956308.2023.2213102': "The document titled 'The Transformative Potential of Generative AI' is a conversation between Jim Euchner and Ethan Mollick, featured in 'Research-Technology Management' from July to August 2023. Ethan Mollick, who has been experimenting with the capabilities of generative AI, emphasizes its unparalleled significance, comparing its immediate impact to the first Internet boom. He mentions his experiences in entrepreneurship and technology and suggests that generative AI has a vast potential, citing studies that indicate performance improvements through its use. The conversation aims to explore the transformative effects of generative AI on organizations and individuals.",
    'http://libproxy.smu.edu.sg/login?url=https://www.proquest.com/docview/2352323896?pq-origsite=primo': "The document discusses the role of the FDA in ensuring the safety of food derived from animals, especially when new expression products are involved. These products could potentially affect the safety of the food, and the FDA's responsibility is to guarantee its safety for consumers and meet international trading standards. The FDA strongly supports the use of genome editing and other innovative technologies to introduce products that can enhance human and animal health, animal well-being, and food production quality. The agency is dedicated to ensuring these products are safe, efficient, and deliver the claimed results, based on rigorous scientific evaluation.",
    'http://libproxy.smu.edu.sg/login?url=https://doi.ieeecomputersociety.org/10.1109/MS.2023.3300574': "The document discusses the vision for integrating Generative AI (GAI) into educational practices rather than instinctively resisting it. Authored by Christopher Bull and Ahmed Kharrufa from Newcastle University's School of Computing, the article highlights the disruptive shift in the software development industry towards using GAI assistants for programming. Tools like GitHub Copilot and ChatGPT are cited as examples that have sparked both enthusiasm and concerns. The potential adaptability of the industry to this change remains uncertain. The document seems to explore the implications and possible applications of generative AI within the context of education and software development.",
}